= firmadigital-libreria

image:https://img.shields.io/maven-central/v/io.github.eduedudev/libreria[link=https://central.sonatype.com/artifact/io.github.eduedudev/libreria]
image:https://github.com/eduedudev/firmadigital-libreria/actions/workflows/ci.yml/badge.svg[link=https://github.com/eduedudev/firmadigital-libreria/actions]

Mirror del proyecto original https://minka.gob.ec/mintel/ge/firmaec/firmadigital-digital[firmadigital-digital] mantenido en GitHub por https://github.com/eduedudev[Eduardo Guastay].

Librería Java para aplicaciones de firma digital (XAdES, PAdES, CAdES).

== Instalación

=== Maven

Agrega esta dependencia a tu `pom.xml`:

[source,xml]
----
<dependency>
    <groupId>io.github.eduedudev</groupId>
    <artifactId>libreria</artifactId>
    <version>5.1.0</version>
</dependency>
----

=== Gradle

[source,groovy]
----
implementation 'io.github.eduedudev:libreria:5.1.0'
----

=== Compilar desde fuente

[source,bash]
----
$ mvn clean package
----

== Introducción

Los siguientes pasos le permitirán obtener una copia del proyecto para correrla en la máquina local para propósitos de desarrollo y pruebas.

== Prerequisitos

=== Java

Se necesita instalar _Java Development Kit (JDK) 17_ para compilar y correr la aplicación.

En Fedora se debe instalar el paquete _java-17-openjdk-devel_:

[source, bash]
----
$ sudo dnf -y install java-17-openjdk-devel
----

En Ubuntu se debe instalar el paquete _openjdk-17-jdk_.

[source, bash]
----
$ sudo apt-get install openjdk-17-jdk
----

=== Maven

Para compilar y empaquetar se utiliza https://maven.apache.org[Apache Maven] versión 3.8.8.

En _Microsoft Windows_ se debe descargar e instalar siguiendo las instrucciones de instalación de https://maven.apache.org/install.html[Apache Maven].

En _Fedora_ se debe instalar el paquete  `maven`:

[source,bash]
----
$ sudo dnf install maven
----

En _Ubuntu_ se debe instalar el paquete `maven`:

[source,bash]
----
$ sudo apt-get install maven
----

=== NetBeans

Se utilizó como entorno de desarrollo el IDE https://netbeans.org[Netbeans].

== Compilar

Se debe compilar usando el siguiente comando:

[source, bash]
----
$ mvn clean package
----

== Colaborar

Para colaborar abre un _Issue_ o _Pull Request_ en https://github.com/eduedudev/firmadigital-libreria[GitHub].

== Autores

* *Eduardo Guastay* - *Mantenimiento* - https://github.com/eduedudev[@eduedudev] - hi@eduedu.dev
* *Ricardo Arguello* - *Desarrollo original* - https://www.soportelibre.com[Soporte Libre]
* *Misael Fernández* - *Desarrollo original* - misael.fernandez.correa@gmail.com
* *Diana Pujol* - *Desarrollo original* - deeperdigitalec@outlook.es

== Licencia

Esta aplicación se distribuye con una licencia https://www.gnu.org/licenses/gpl.html[GPLv3].

Este proyecto utiliza la biblioteca Digital Signature Service (DSS) de la Unión Europea, 
bajo los términos de la licencia EUPL 1.2.

- Texto completo de la licencia: https://interoperable-europe.ec.europa.eu/collection/eupl/eupl-text-eupl-12
- Información del proyecto DSS: https://ec.europa.eu/digital-building-blocks/code/projects/ESIG-DSS
