= Rubrica: Librería para Firma Digital


== Introducción

Rubrica es una librería Java para aplicaciones de firma digital licenciada como software libre mediante una licencia AGPL v3.

=== Prerequisitos

==== Java
Se necesita instalar _Java Development Kit (JDK) 8_ para compilar y correr la aplicación.

En Microsoft Windows se debe descargar de la página de descargas en http://www.oracle.com/technetwork/java/javase/downloads/[Java SE Downloads].

En Fedora se debe instalar el paquete _java-1.8.0-openjdk-devel_:

[source, bash]
----
$ sudo dnf install java-1.8.0-openjdk-devel
----

En Ubuntu se debe instalar el paquete _openjdk-8-jdk_.

[source, bash]
----
$ sudo apt-get install openjdk-8-jdk
----


== Dependencias

* iText7: https://github.com/itext/itext7
* OpenPDF: https://github.com/LibrePDF/OpenPDF
* BouncyCastle: https://www.bouncycastle.org


== Compilación

Una vez instalados los pre-requisitos se puede compilar usando Maven:

----
mvn clean install
----


== Uso

Para usarlo como una dependencia en Maven (pom.xml):

----
<dependency>
  <groupId>io.rubrica</groupId>
  <artifactId>rubrica</artifactId>
  <version>0.1.8</version>
</dependency>
----


== Licencia

https://www.gnu.org/licenses/agpl-3.0.txt[GNU AFFERO GENERAL PUBLIC LICENSE, Version 3 (AGPL-3.0)]


== Contacto

Ricardo Arguello: ricardo.arguello AT soportelibre.com
